CREATE TABLE USER_HANDLE (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USER_NAME VARCHAR(28) NOT NULL,
	GAME INTEGER NOT NULL,
	HANDLE_INDEX INTEGER NOT NULL,
	HANDLE VARCHAR(19) NOT NULL
);
CREATE UNIQUE INDEX UNIQUE_USER_INDEX ON USER_HANDLE(USER_NAME, GAME, HANDLE_INDEX);
CREATE UNIQUE INDEX UNIQUE_HANDLE ON USER_HANDLE(GAME, HANDLE);

CREATE TABLE USER_EXTRAMEM (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USER_NAME VARCHAR(28) NOT NULL,
	GAME INTEGER NOT NULL,
	EXTRAMEM BLOB
);
CREATE UNIQUE INDEX UNIQUE_EXTRAMEM_INDEX ON USER_EXTRAMEM(USER_NAME, GAME);
